import { Doctor, Role } from './types';

export const DOCTOR_PLACEHOLDER_IMAGE = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIiBmaWxsPSIjRTJFOEYwIj48cmVjdCB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgcng9IjUwIiAvPjxnIGZpbGw9IiNBMDBBRUMwIj48Y2lyY2xlIGN4PSI1MCIgY3k9IjQwIiIHIj0iMTUiIC8+PHBhdGggZD0iTTI1LDkwIEMyNSw3MCA3NSw3MCA3NSw5MCBaIiAvPjxwYXRoIGQ9Ik02OCw1MiBhMTgsMTggMCAwLDAtMzYsMCIgc3Ryb2tlPSIjQTAwQUVDMCIgc3Ryb2tlLXdpZHRoPSIzIiBmaWxsPSJub25lIiAvPjxjaXJjbGUgY3g9IjMwIiBjeT0iNTUiIHI9IjQiLz48Y2lyY2xlIGN4PSI3MCIgY3k9IjU1IiIHIj0iNCIvPjxjaXJjbGUgY3g9IjUwIiBjeT0iODAiIHI9IjgiIGZpbGw9IiNFMkU4RjAiIHN0cm9rZT0iI0EwMEFFQzAiIHN0cm9rZS13aWR0aD0iMyIvPjwvZz48L3N2Zz4=';

// Use Vite's environment variable or default to localhost. 
// The vite proxy handles '/api' requests locally.
export const API_BASE_URL = (import.meta as any).env?.VITE_API_URL || 'http://localhost:5000';